nginx:
  image: nginx:alpine
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  volumes:
    - ./www/data:/var/www/html/:rw
    - ./www/p:/var/www/p/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  restart: unless-stopped

aria2:
    container_name: Aria2
    image: abcminiuser/docker-aria2-with-webui:latest
    net: "bridge"
    ports:
      - 6800:6800
      - 6880:80
    volumes:
      - ./www:/data
      - ./conf/Aria2:/conf
    environment:
      - PGID=1001
      - PUID=1001
    restart: unless-stopped
ss:
    container_name: shadowsocks
    image: easypi/shadowsocks-libev
    ports:
      - "11678:8388/tcp"
      - "11678:8388/udp"
    environment:
      - METHOD=aes-256-cfb
      - PASSWORD=liugeyi
    restart: always
bt:
    container_name: transmission
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./www/data:/downloads
      - ./conf/bt:/config
      - ./www/data:/watch
    environment:
      - TZ=Europe/London
      - PGID=1001
      - PUID=1001
